remote_theme: CloudCannon/base-jekyll-template@main
plugins:
- jekyll-remote-theme

title: Cap Recognizer
description: An image classification API that classifies 20 different types of caps around the woeld

author:
  name: Mohammad Faiyaz Uz Zaman
