remote_theme = midnight@master
plugins:
- jekyll-remote-theme

title: Cap Recognizer
description: An image classification API that classifies 20 different types of caps around the woeld

author:
  name: Mohammad Faiyaz Uz Zaman
  